### ISSUE TITLE
wallet Hardware Installation / Creation Stucks on "Continue" after inserting the Pin and connecting my ledger

### ISSUE THREAD

**Issue by Schorse88** [iotaledger/firefly#1403]
## Issue description

wallet Hardware Installation / Creation Stucks on "Continue" after inserting the Pin and connecting my ledger. After klicking "Continue" nothing happens (short flashing message: "Creating Wallet please wait")

## Wallet version

Firefly 1.2.0

- wallet version (version number, commit, or branch):

## System specification

Windows 10 64bit

Mac/Win/Linux (+Version and or Distro if possible)

## Is it a repeatable issue?

Yes, tried it on 2 Computers, PC and Laptop

## Steps To reproduce the issue

Explain how the maintainer can reproduce the issue.

1. Open firefly-desktop-1.2.0.exe
2. Install
3. Choose Create Hardware Wallet
4. Follow all steps
5. Last step before Creating the Wallet is : Push Button "Continue"
6. Push the Button (Message: Creating Wallet pls Wait apears for half second) - Nothing happens

## Expected behaviour

Creating the Wallet?

## Actual behaviour

Nothing happens.

## Errors

No errors, No Error-Log was created
![Firefly](https://user-images.githubusercontent.com/78955905/129445646-6ca9ef08-2194-4e4f-812f-1416c4763255.gif)
.

**Comment by maxwellmattryan** [comment]
Hey @Schorse88 some other Windows users have faced issues like this that were due to connectivity problems. Have you tried connecting directly into the computer (i.e. not a dock) and also using a different cable (ideally the one that came with the Ledger device originally)?

**Comment by teunvw14** [comment]
Also have the exact same issue on Windows 10 / Firefly 1.2.0 using Ledger Nano S. Even connecting the Ledger directly to the USB ports on my motherboard, the issue still happens. Currently unable to make a Ledger profile due to this.

**Comment by teunvw14** [comment]
I fixed this by updating to a new firmware version (2.0). From Ledger Live I got the impression that I wasn't yet able to upgrade. I downloaded the latest Ledger Live from the website (updating inside Ledger Live was bugged, hence - supposedly - why I couldn't upgrade the Ledger firmware). That made the firmware upgrade available. After that, creating the Ledger profile worked just fine. 🎉 🎉

**Comment by Schorse88** [comment]
I fixed it in the same way👍

Teun van Wezel ***@***.***> schrieb am Mi. 18. Aug. 2021 um
00:12:

**Comment by Geronimo1982** [comment]
i do have firmware version 3.5. Do i have to re-install windows 2.0? in my first try, windows was blocking my installation of version 2.0

**Comment by teunvw14** [comment]
@Geronimo1982 I don't really understand your comment, but if you're experiencing the issue described, I'd recommend trying to upgrade your Ledger firmware. You should be able to do this from Ledger Live, but you might need to update to the latest version: [ledger.com/ledger-live](https://www.ledger.com/ledger-live)

**Comment by Geronimo1982** [comment]
i thougt you spoke about windows firmware . I've already updated ledger live firmware but it's still not workin

**Comment by teunvw14** [comment]
@Geronimo1982 You need to update the firmware of your Ledger device, see below links for reference:
Nano S: https://support.ledger.com/hc/en-us/articles/360002731113-Update-Ledger-Nano-S-firmware?docs=true
Nano X: https://support.ledger.com/hc/en-us/articles/360013349800-Update-Ledger-Nano-X-firmware?docs=true

**Comment by Geronimo1982** [comment]
Thx much Teun, it works

**Comment by MiKeF05** [comment]
I guess this issue can be closed as the problem was an outdated firmware ledger version.
