### ISSUE TITLE
PIN incorrect error - when using the correct PIN code -

### ISSUE THREAD

**Issue by Yanev1** [iotaledger/firefly#1622]
### Issue description

I am using a Firefly wallet on a Mac (Big Sur v. 11.6), and I've logged in before without any issues using my pin. 
When I tried doing that today, after a few months since I migrated to the Firefly App, it started showing me an 'incorrect attempt'  error whenever I try to log in with my PIN code. I am 100% sure that the PIN is correct, as I am the only one who has access to my account and have not changed it since I migrated to Firefly. I even deleted and reinstalled the app again, and it still wouldn't accept my PIN.

### Firefly version

1.2.0

### OS details

macOS Big Sur version 11.6

### Can the issue be reliably reproduced?

Yes

### Steps to reproduce the issue

1. Click on your profile
2. Enter a wrong pin code
3. Enter the correct pin code
...

### Expected behaviour

Access your account wallet

### Actual behaviour

Error message telling you an incorrect pin was used

### Errors

'1 incorrect attempt'
On the next try:
'2 incorrect attempts'....

**Comment by ocompagne** [comment]
I experience the same problem. I updated Firefly hoping to fix it, from 1.0.0 to 1.2.0. Same issue. 
And I am 100% certain this is the correct PIN.

**Comment by Yanev1** [comment]
Yes me too! 1000% I'm using the correct PIN, yet it wouldn't accept it. The most frustrating part of it all is that there's no feedback to an issue like this, and I'm locked out of my crypto... Honestly, I'm losing my faith in IOTA as each day goes by...

**Comment by ocompagne** [comment]
I was able to go around it by creating a new profile and using the pass phrase. But yeah, that's a major wallet issue, I'm surprised there isn't more reaction from the devs. 

That being said it looks like the entire repo isn't updated much. The last update was 12 days ago, and a lot of the files haven't been updated in 2-3 months. Um..

**Comment by Yanev1** [comment]
Thanks for the tip, I guess if there's no other option I'll go that route as well...

**Comment by nicole-obrien** [comment]
Hi @Yanev1, was you able to access your funds on a new profile?

**Comment by Yanev1** [comment]
Yes I was. It's really frustrating though that a bug like that exists and no one does anything...

**Comment by steffenroeber** [comment]
Same for me. Incorrect PIN comparison is very poor for a wallet that secures real money...

**Comment by MiKeF05** [comment]
This issue should be solved with v1.3. Can you check this? May be neccessary to create a new profile and restore your wallet.

**Comment by steffenroeber** [comment]
@MiKeF05  Impossible to say if the version fixes the problem because PINs were removed from credentials manager due to unknown reason as described here: #1683.
After looking into fix commit, its hard to say if this fixes the problem.
Would be nice if someone of Firefly teams could answer the questions from #1683.

**Comment by MiKeF05** [comment]
@steffenroeber But as I understand it the PINs were only removed from the credential manager on Windows. In this case the OS is  macOS.

**Comment by nicole-obrien** [comment]
Duplicate of #1117

**Comment by dialex** [comment]
This is still not solved! I'm using 1.3.3 on MacOS and I'm having the same issue.
I tried creating a new profile, restoring my wallet with the recovery phrase but it says I only have 20 words instead of 24. Look, I'm getting very nervous. What the hell is happening with my wallet?

**Comment by dialex** [comment]
Any update on this?

**Comment by MiKeF05** [comment]
The recovery phrase has 24 words not 20 words. You can either recover your wallet with your 24 words phrase or with the stronghold backup file + password.

**Comment by dialex** [comment]
I tried again and found out the issue. I have my recovery phrase splitted into 5 lines. I copy-pasted that into Firefly and it said I had only 20 words. So what I think is happening is that Firefly is ignoring the line break, and concatenating the last and first word of every line, yielding the 20 words.

As a user, I expected Firefly to treat a line break as a space. That's what all the wallets I used to far do.

**Comment by FrankThode** [comment]
Your keys - not your IOTA................Any news on this? 
Same issue: 100% the pin is correct. But it says wrong pin.  - what a catastrophic bug, that makes me loose complete faith in IOTA project. THIS - MUST -  NEVER EVER - HAPPEN IN ANY WALLET!

**Comment by MarkyabaDev** [comment]
This happened to me today on both the standard firefly and firefly shimmer wallets at the same time. Definitely have the correct pins but I get the incorrect pin message.
