### ISSUE TITLE
Version 1.3.0: Staking not detected

### ISSUE THREAD

**Issue by jperece** [iotaledger/firefly#1827]
### Issue description

I can't participate in prestaking because my node don't let it. I've prove with manual and automatic one (advance setting - Network)

### Firefly version

1.3.0

### OS details

macOS Monterey - 12.0.1

### Can the issue be reliably reproduced?

Yes

### Steps to reproduce the issue

1. Open Firefly
2. Click Stake icon
3. Staking not detected message appears and the buttom is unavailable.
...

### Expected behaviour

allow participate in staking

### Actual behaviour

-

### Errors

Tue, 21 Dec 2021 14:57:54 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.cafe/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:57:44 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.cafe/api/v1/info): connection closed before message completed`
<img width="1392" alt="Captura de pantalla 2021-12-21 a las 15 41 07" src="https://user-images.githubusercontent.com/56755131/146951202-39c943b1-6833-47f5-98d3-33df763fe0b9.png">

Tue, 21 Dec 2021 14:57:14 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.cafe/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:56:54 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.cafe/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:56:34 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.cafe/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:56:24 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.cafe/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:56:14 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.cafe/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:56:04 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.cafe/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:55:34 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.cafe/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:55:24 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.cafe/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:55:04 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.cafe/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:54:54 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.cafe/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:54:24 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.cafe/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:54:14 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.cafe/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:53:25 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.cafe/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:53:14 GMT
ReqwestError: error sending request for url (https://chrysalis-nodes.iota.cafe/api/plugins/participation/events/57607d9f8cefc366c3ead71f5b1d76cef1b36a07eb775158c541107951d4aecb/status): connection closed before message completed

Tue, 21 Dec 2021 14:53:14 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.cafe/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:53:04 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.cafe/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:52:54 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.cafe/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:52:44 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.cafe/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:52:34 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.cafe/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:52:25 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.cafe/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:52:15 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.cafe/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:52:05 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.cafe/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:51:55 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.cafe/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:51:44 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.cafe/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:51:24 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.cafe/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:50:55 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.cafe/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:50:44 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.cafe/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:50:34 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.cafe/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:50:24 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.cafe/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:50:14 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.cafe/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:50:04 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.cafe/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:49:54 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.cafe/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:49:45 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.cafe/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:49:40 GMT
ReqwestError: error sending request for url (https://chrysalis-nodes.iota.cafe/api/plugins/participation/events): channel closed

Tue, 21 Dec 2021 14:49:24 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.cafe/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:49:14 GMT
ReqwestError: error sending request for url (https://chrysalis-nodes.iota.cafe/api/plugins/participation/addresses/iota1qqc2nastd4q27antnttxrn22yxuup34rx5q5w3n4lkaxdcwy6ymjwxayhsd): connection closed before message completed

Tue, 21 Dec 2021 14:49:14 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/addresses/iota1qqc2nastd4q27antnttxrn22yxuup34rx5q5w3n4lkaxdcwy6ymjwxayhsd/outputs): connection closed before message completed`

Tue, 21 Dec 2021 14:49:14 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.cafe/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:49:14 GMT
ReqwestError: error sending request for url (https://chrysalis-nodes.iota.cafe/api/plugins/participation/events/57607d9f8cefc366c3ead71f5b1d76cef1b36a07eb775158c541107951d4aecb): connection closed before message completed

Tue, 21 Dec 2021 14:48:44 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.cafe/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:48:43 GMT
ReqwestError: error sending request for url (https://chrysalis-nodes.iota.cafe/api/plugins/participation/addresses/iota1qrxneg8pn7yau6huz37lvr0u354pym8jvd0ajuvghmmlfr6m7ewp6rmsha5): connection closed before message completed

Tue, 21 Dec 2021 14:48:35 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.cafe/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:48:33 GMT
ReqwestError: error sending request for url (https://chrysalis-nodes.iota.cafe/api/plugins/participation/addresses/iota1qq4hmfexn8eexa6l3rg5pr0mcf42clzrh79mvq3mlne5n5vu2fp2508kwv4): connection closed before message completed

Tue, 21 Dec 2021 14:48:24 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.cafe/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:48:23 GMT
ReqwestError: error sending request for url (https://chrysalis-nodes.iota.cafe/api/plugins/participation/addresses/iota1qqc2nastd4q27antnttxrn22yxuup34rx5q5w3n4lkaxdcwy6ymjwxayhsd): connection closed before message completed

Tue, 21 Dec 2021 14:48:14 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.cafe/api/v1/info): channel closed`

Tue, 21 Dec 2021 14:48:13 GMT
ReqwestError: error sending request for url (https://chrysalis-nodes.iota.cafe/api/plugins/participation/addresses/iota1qqc2nastd4q27antnttxrn22yxuup34rx5q5w3n4lkaxdcwy6ymjwxayhsd): connection closed before message completed

Tue, 21 Dec 2021 14:48:04 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.cafe/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:48:03 GMT
ReqwestError: error sending request for url (https://chrysalis-nodes.iota.cafe/api/plugins/participation/addresses/iota1qqc2nastd4q27antnttxrn22yxuup34rx5q5w3n4lkaxdcwy6ymjwxayhsd): connection closed before message completed

Tue, 21 Dec 2021 14:47:54 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.cafe/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:47:44 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.cafe/api/v1/info): channel closed`

Tue, 21 Dec 2021 14:47:43 GMT
ReqwestError: error sending request for url (https://chrysalis-nodes.iota.cafe/api/plugins/participation/addresses/iota1qz0yvghgxppujggra4dc30260gv0s2fkuuy99427wpdauvm6379z7v4t204): error trying to connect: tls handshake eof

Tue, 21 Dec 2021 14:47:34 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.cafe/api/v1/info): connection error: Connection reset by peer (os error 54)`

Tue, 21 Dec 2021 14:47:33 GMT
ReqwestError: error sending request for url (https://chrysalis-nodes.iota.cafe/api/plugins/participation/addresses/iota1qqc2nastd4q27antnttxrn22yxuup34rx5q5w3n4lkaxdcwy6ymjwxayhsd): connection closed before message completed

Tue, 21 Dec 2021 14:47:24 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.cafe/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:47:23 GMT
ReqwestError: error sending request for url (https://chrysalis-nodes.iota.cafe/api/plugins/participation/addresses/iota1qz0yvghgxppujggra4dc30260gv0s2fkuuy99427wpdauvm6379z7v4t204): connection closed before message completed

Tue, 21 Dec 2021 14:47:15 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.cafe/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:47:13 GMT
ReqwestError: error sending request for url (https://chrysalis-nodes.iota.cafe/api/plugins/participation/addresses/iota1qqc2nastd4q27antnttxrn22yxuup34rx5q5w3n4lkaxdcwy6ymjwxayhsd): connection closed before message completed

Tue, 21 Dec 2021 14:47:04 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.cafe/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:47:03 GMT
ReqwestError: error sending request for url (https://chrysalis-nodes.iota.cafe/api/plugins/participation/addresses/iota1qqc2nastd4q27antnttxrn22yxuup34rx5q5w3n4lkaxdcwy6ymjwxayhsd): connection closed before message completed

Tue, 21 Dec 2021 14:46:54 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.cafe/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:46:53 GMT
ReqwestError: error sending request for url (https://chrysalis-nodes.iota.cafe/api/plugins/participation/addresses/iota1qz0yvghgxppujggra4dc30260gv0s2fkuuy99427wpdauvm6379z7v4t204): connection closed before message completed

Tue, 21 Dec 2021 14:46:52 GMT
ReqwestError: error sending request for url (https://chrysalis-nodes.iota.cafe/api/plugins/participation/events): connection closed before message completed

Tue, 21 Dec 2021 14:46:43 GMT
ReqwestError: error sending request for url (https://chrysalis-nodes.iota.cafe/api/plugins/participation/addresses/iota1qz0yvghgxppujggra4dc30260gv0s2fkuuy99427wpdauvm6379z7v4t204): connection closed before message completed

Tue, 21 Dec 2021 14:46:33 GMT
ReqwestError: error sending request for url (https://chrysalis-nodes.iota.cafe/api/plugins/participation/addresses/iota1qqc2nastd4q27antnttxrn22yxuup34rx5q5w3n4lkaxdcwy6ymjwxayhsd): error trying to connect: Connection reset by peer (os error 54)

Tue, 21 Dec 2021 14:46:24 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.cafe/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:46:23 GMT
ReqwestError: error sending request for url (https://chrysalis-nodes.iota.cafe/api/plugins/participation/addresses/iota1qz0yvghgxppujggra4dc30260gv0s2fkuuy99427wpdauvm6379z7v4t204): connection closed before message completed

Tue, 21 Dec 2021 14:46:14 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.cafe/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:46:13 GMT
ReqwestError: error sending request for url (https://chrysalis-nodes.iota.cafe/api/plugins/participation/addresses/iota1qz0yvghgxppujggra4dc30260gv0s2fkuuy99427wpdauvm6379z7v4t204): connection closed before message completed

Tue, 21 Dec 2021 14:46:04 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.cafe/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:46:03 GMT
ReqwestError: error sending request for url (https://chrysalis-nodes.iota.cafe/api/plugins/participation/addresses/iota1qz0yvghgxppujggra4dc30260gv0s2fkuuy99427wpdauvm6379z7v4t204): connection closed before message completed

Tue, 21 Dec 2021 14:45:43 GMT
ReqwestError: error sending request for url (https://chrysalis-nodes.iota.cafe/api/plugins/participation/addresses/iota1qqc2nastd4q27antnttxrn22yxuup34rx5q5w3n4lkaxdcwy6ymjwxayhsd): connection closed before message completed

Tue, 21 Dec 2021 14:45:34 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.cafe/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:45:33 GMT
ReqwestError: error sending request for url (https://chrysalis-nodes.iota.cafe/api/plugins/participation/addresses/iota1qqc2nastd4q27antnttxrn22yxuup34rx5q5w3n4lkaxdcwy6ymjwxayhsd): connection closed before message completed

Tue, 21 Dec 2021 14:45:31 GMT
ReqwestError: error sending request for url (https://chrysalis-nodes.iota.cafe/api/plugins/participation/events/57607d9f8cefc366c3ead71f5b1d76cef1b36a07eb775158c541107951d4aecb): connection closed before message completed

Tue, 21 Dec 2021 14:45:24 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.cafe/api/v1/info): channel closed`

Tue, 21 Dec 2021 14:45:23 GMT
ReqwestError: error sending request for url (https://chrysalis-nodes.iota.cafe/api/plugins/participation/addresses/iota1qqc2nastd4q27antnttxrn22yxuup34rx5q5w3n4lkaxdcwy6ymjwxayhsd): connection closed before message completed

Tue, 21 Dec 2021 14:45:21 GMT
ReqwestError: error sending request for url (https://chrysalis-nodes.iota.cafe/api/plugins/participation/events/57607d9f8cefc366c3ead71f5b1d76cef1b36a07eb775158c541107951d4aecb): connection closed before message completed

Tue, 21 Dec 2021 14:45:14 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.cafe/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:45:05 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:45:02 GMT
ReqwestError: error sending request for url (https://chrysalis-nodes.iota.org/api/plugins/participation/addresses/iota1qrxneg8pn7yau6huz37lvr0u354pym8jvd0ajuvghmmlfr6m7ewp6rmsha5): connection closed before message completed

Tue, 21 Dec 2021 14:44:54 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): channel closed`

Tue, 21 Dec 2021 14:44:53 GMT
ReqwestError: error sending request for url (https://chrysalis-nodes.iota.org/api/plugins/participation/addresses/iota1qqc2nastd4q27antnttxrn22yxuup34rx5q5w3n4lkaxdcwy6ymjwxayhsd): connection closed before message completed

Tue, 21 Dec 2021 14:44:43 GMT
ReqwestError: error sending request for url (https://chrysalis-nodes.iota.org/api/plugins/participation/addresses/iota1qz0yvghgxppujggra4dc30260gv0s2fkuuy99427wpdauvm6379z7v4t204): channel closed

Tue, 21 Dec 2021 14:44:34 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:44:23 GMT
ReqwestError: error sending request for url (https://chrysalis-nodes.iota.org/api/plugins/participation/addresses/iota1qq4hmfexn8eexa6l3rg5pr0mcf42clzrh79mvq3mlne5n5vu2fp2508kwv4): connection closed before message completed

Tue, 21 Dec 2021 14:44:04 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:44:02 GMT
ReqwestError: error sending request for url (https://chrysalis-nodes.iota.org/api/plugins/participation/addresses/iota1qz0yvghgxppujggra4dc30260gv0s2fkuuy99427wpdauvm6379z7v4t204): connection closed before message completed

Tue, 21 Dec 2021 14:43:54 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:43:54 GMT
ReqwestError: error sending request for url (https://chrysalis-nodes.iota.org/api/plugins/participation/addresses/iota1qqc2nastd4q27antnttxrn22yxuup34rx5q5w3n4lkaxdcwy6ymjwxayhsd): connection closed before message completed

Tue, 21 Dec 2021 14:43:33 GMT
ReqwestError: error sending request for url (https://chrysalis-nodes.iota.org/api/plugins/participation/addresses/iota1qqc2nastd4q27antnttxrn22yxuup34rx5q5w3n4lkaxdcwy6ymjwxayhsd): connection closed before message completed

Tue, 21 Dec 2021 14:43:03 GMT
ReqwestError: error sending request for url (https://chrysalis-nodes.iota.org/api/plugins/participation/addresses/iota1qqc2nastd4q27antnttxrn22yxuup34rx5q5w3n4lkaxdcwy6ymjwxayhsd): channel closed

Tue, 21 Dec 2021 14:42:54 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:42:53 GMT
ReqwestError: error sending request for url (https://chrysalis-nodes.iota.org/api/plugins/participation/addresses/iota1qqc2nastd4q27antnttxrn22yxuup34rx5q5w3n4lkaxdcwy6ymjwxayhsd): connection closed before message completed

Tue, 21 Dec 2021 14:42:44 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): channel closed`

Tue, 21 Dec 2021 14:42:43 GMT
ReqwestError: error sending request for url (https://chrysalis-nodes.iota.org/api/plugins/participation/addresses/iota1qqc2nastd4q27antnttxrn22yxuup34rx5q5w3n4lkaxdcwy6ymjwxayhsd): channel closed

Tue, 21 Dec 2021 14:42:35 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:42:33 GMT
ReqwestError: error sending request for url (https://chrysalis-nodes.iota.org/api/plugins/participation/addresses/iota1qqc2nastd4q27antnttxrn22yxuup34rx5q5w3n4lkaxdcwy6ymjwxayhsd): connection closed before message completed

Tue, 21 Dec 2021 14:42:23 GMT
ReqwestError: error sending request for url (https://chrysalis-nodes.iota.org/api/plugins/participation/addresses/iota1qz0yvghgxppujggra4dc30260gv0s2fkuuy99427wpdauvm6379z7v4t204): connection closed before message completed

Tue, 21 Dec 2021 14:42:14 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:42:13 GMT
ReqwestError: error sending request for url (https://chrysalis-nodes.iota.org/api/plugins/participation/addresses/iota1qz0yvghgxppujggra4dc30260gv0s2fkuuy99427wpdauvm6379z7v4t204): connection closed before message completed

Tue, 21 Dec 2021 14:42:04 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:42:03 GMT
ReqwestError: error sending request for url (https://chrysalis-nodes.iota.org/api/plugins/participation/addresses/iota1qqc2nastd4q27antnttxrn22yxuup34rx5q5w3n4lkaxdcwy6ymjwxayhsd): connection closed before message completed

Tue, 21 Dec 2021 14:41:44 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:41:43 GMT
ReqwestError: error sending request for url (https://chrysalis-nodes.iota.org/api/plugins/participation/addresses/iota1qqc2nastd4q27antnttxrn22yxuup34rx5q5w3n4lkaxdcwy6ymjwxayhsd): channel closed

Tue, 21 Dec 2021 14:41:35 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): channel closed`

Tue, 21 Dec 2021 14:41:33 GMT
ReqwestError: error sending request for url (https://chrysalis-nodes.iota.org/api/plugins/participation/addresses/iota1qqc2nastd4q27antnttxrn22yxuup34rx5q5w3n4lkaxdcwy6ymjwxayhsd): connection closed before message completed

Tue, 21 Dec 2021 14:41:23 GMT
ReqwestError: error sending request for url (https://chrysalis-nodes.iota.org/api/plugins/participation/addresses/iota1qqc2nastd4q27antnttxrn22yxuup34rx5q5w3n4lkaxdcwy6ymjwxayhsd): channel closed

Tue, 21 Dec 2021 14:41:13 GMT
ReqwestError: error sending request for url (https://chrysalis-nodes.iota.org/api/plugins/participation/addresses/iota1qqc2nastd4q27antnttxrn22yxuup34rx5q5w3n4lkaxdcwy6ymjwxayhsd): connection closed before message completed

Tue, 21 Dec 2021 14:41:04 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:41:03 GMT
ReqwestError: error sending request for url (https://chrysalis-nodes.iota.org/api/plugins/participation/addresses/iota1qqc2nastd4q27antnttxrn22yxuup34rx5q5w3n4lkaxdcwy6ymjwxayhsd): connection closed before message completed

Tue, 21 Dec 2021 14:40:54 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:40:52 GMT
ReqwestError: error sending request for url (https://chrysalis-nodes.iota.org/api/plugins/participation/addresses/iota1qz0yvghgxppujggra4dc30260gv0s2fkuuy99427wpdauvm6379z7v4t204): connection closed before message completed

Tue, 21 Dec 2021 14:40:45 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:40:34 GMT
ReqwestError: error sending request for url (https://chrysalis-nodes.iota.org/api/plugins/participation/addresses/iota1qqc2nastd4q27antnttxrn22yxuup34rx5q5w3n4lkaxdcwy6ymjwxayhsd): channel closed

Tue, 21 Dec 2021 14:40:24 GMT
ReqwestError: error sending request for url (https://chrysalis-nodes.iota.org/api/plugins/participation/addresses/iota1qqc2nastd4q27antnttxrn22yxuup34rx5q5w3n4lkaxdcwy6ymjwxayhsd): connection closed before message completed

Tue, 21 Dec 2021 14:40:14 GMT
ReqwestError: error sending request for url (https://chrysalis-nodes.iota.org/api/plugins/participation/addresses/iota1qqc2nastd4q27antnttxrn22yxuup34rx5q5w3n4lkaxdcwy6ymjwxayhsd): connection closed before message completed

Tue, 21 Dec 2021 14:40:06 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:40:03 GMT
ReqwestError: error sending request for url (https://chrysalis-nodes.iota.org/api/plugins/participation/addresses/iota1qqc2nastd4q27antnttxrn22yxuup34rx5q5w3n4lkaxdcwy6ymjwxayhsd): connection closed before message completed

Tue, 21 Dec 2021 14:39:55 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:39:53 GMT
ReqwestError: error sending request for url (https://chrysalis-nodes.iota.org/api/plugins/participation/addresses/iota1qz0yvghgxppujggra4dc30260gv0s2fkuuy99427wpdauvm6379z7v4t204): connection closed before message completed

Tue, 21 Dec 2021 14:39:45 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:39:43 GMT
ReqwestError: error sending request for url (https://chrysalis-nodes.iota.org/api/plugins/participation/addresses/iota1qz0yvghgxppujggra4dc30260gv0s2fkuuy99427wpdauvm6379z7v4t204): connection closed before message completed

Tue, 21 Dec 2021 14:39:33 GMT
ReqwestError: error sending request for url (https://chrysalis-nodes.iota.org/api/plugins/participation/addresses/iota1qz0yvghgxppujggra4dc30260gv0s2fkuuy99427wpdauvm6379z7v4t204): connection closed before message completed

Tue, 21 Dec 2021 14:39:15 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:39:13 GMT
ReqwestError: error sending request for url (https://chrysalis-nodes.iota.org/api/plugins/participation/addresses/iota1qqc2nastd4q27antnttxrn22yxuup34rx5q5w3n4lkaxdcwy6ymjwxayhsd): connection closed before message completed

Tue, 21 Dec 2021 14:39:05 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:39:03 GMT
ReqwestError: error sending request for url (https://chrysalis-nodes.iota.org/api/plugins/participation/addresses/iota1qz0yvghgxppujggra4dc30260gv0s2fkuuy99427wpdauvm6379z7v4t204): connection closed before message completed

Tue, 21 Dec 2021 14:38:53 GMT
ReqwestError: error sending request for url (https://chrysalis-nodes.iota.org/api/plugins/participation/addresses/iota1qqc2nastd4q27antnttxrn22yxuup34rx5q5w3n4lkaxdcwy6ymjwxayhsd): connection closed before message completed

Tue, 21 Dec 2021 14:38:45 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:38:43 GMT
ReqwestError: error sending request for url (https://chrysalis-nodes.iota.org/api/plugins/participation/addresses/iota1qz0yvghgxppujggra4dc30260gv0s2fkuuy99427wpdauvm6379z7v4t204): connection closed before message completed

Tue, 21 Dec 2021 14:38:36 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:38:33 GMT
ReqwestError: error sending request for url (https://chrysalis-nodes.iota.org/api/plugins/participation/addresses/iota1qz0yvghgxppujggra4dc30260gv0s2fkuuy99427wpdauvm6379z7v4t204): channel closed

Tue, 21 Dec 2021 14:38:24 GMT
ReqwestError: error sending request for url (https://chrysalis-nodes.iota.org/api/plugins/participation/addresses/iota1qq4hmfexn8eexa6l3rg5pr0mcf42clzrh79mvq3mlne5n5vu2fp2508kwv4): connection closed before message completed

Tue, 21 Dec 2021 14:38:23 GMT
ReqwestError: error sending request for url (https://chrysalis-nodes.iota.org/api/plugins/participation/events): connection closed before message completed

Tue, 21 Dec 2021 14:38:14 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:38:13 GMT
ReqwestError: error sending request for url (https://chrysalis-nodes.iota.org/api/plugins/participation/addresses/iota1qqc2nastd4q27antnttxrn22yxuup34rx5q5w3n4lkaxdcwy6ymjwxayhsd): error trying to connect: tls handshake eof

Tue, 21 Dec 2021 14:37:54 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:37:53 GMT
ReqwestError: error sending request for url (https://chrysalis-nodes.iota.org/api/plugins/participation/addresses/iota1qqc2nastd4q27antnttxrn22yxuup34rx5q5w3n4lkaxdcwy6ymjwxayhsd): connection closed before message completed

Tue, 21 Dec 2021 14:37:44 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:37:42 GMT
ReqwestError: error sending request for url (https://chrysalis-nodes.iota.org/api/plugins/participation/addresses/iota1qqc2nastd4q27antnttxrn22yxuup34rx5q5w3n4lkaxdcwy6ymjwxayhsd): connection closed before message completed

Tue, 21 Dec 2021 14:37:35 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.cafe/api/v1/addresses/iota1qqc2nastd4q27antnttxrn22yxuup34rx5q5w3n4lkaxdcwy6ymjwxayhsd/outputs?include-spent=true): connection closed before message completed`

Tue, 21 Dec 2021 14:37:32 GMT
ReqwestError: error sending request for url (https://chrysalis-nodes.iota.org/api/plugins/participation/events/57607d9f8cefc366c3ead71f5b1d76cef1b36a07eb775158c541107951d4aecb): connection closed before message completed

Tue, 21 Dec 2021 14:34:53 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:34:43 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:34:33 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:34:13 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:33:53 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:33:51 GMT
ReqwestError: error sending request for url (https://chrysalis-nodes.iota.org/api/plugins/participation/events): connection closed before message completed

Tue, 21 Dec 2021 14:33:33 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:33:23 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:33:13 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:33:03 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:32:53 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:32:43 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:32:23 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:32:13 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:32:03 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): channel closed`

Tue, 21 Dec 2021 14:31:53 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:31:48 GMT
ReqwestError: error sending request for url (https://chrysalis-nodes.iota.org/api/plugins/participation/events): connection closed before message completed

Tue, 21 Dec 2021 14:31:23 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:31:19 GMT
ReqwestError: error sending request for url (https://chrysalis-nodes.iota.cafe/api/plugins/participation/events): connection closed before message completed

Tue, 21 Dec 2021 14:30:53 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:30:23 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:30:13 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:30:03 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): channel closed`

Tue, 21 Dec 2021 14:29:53 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:29:43 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:29:33 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:29:24 GMT
ReqwestError: error sending request for url (https://chrysalis-nodes.iota.org/api/plugins/participation/events/57607d9f8cefc366c3ead71f5b1d76cef1b36a07eb775158c541107951d4aecb): connection closed before message completed

Tue, 21 Dec 2021 14:29:23 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:29:03 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/addresses/iota1qrxneg8pn7yau6huz37lvr0u354pym8jvd0ajuvghmmlfr6m7ewp6rmsha5/outputs): connection closed before message completed`

Tue, 21 Dec 2021 14:29:03 GMT
ReqwestError: error sending request for url (https://chrysalis-nodes.iota.org/api/plugins/participation/addresses/iota1qqc2nastd4q27antnttxrn22yxuup34rx5q5w3n4lkaxdcwy6ymjwxayhsd): channel closed

Tue, 21 Dec 2021 14:29:02 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:29:02 GMT
ReqwestError: error sending request for url (https://chrysalis-nodes.iota.org/api/plugins/participation/events/57607d9f8cefc366c3ead71f5b1d76cef1b36a07eb775158c541107951d4aecb): connection closed before message completed

Tue, 21 Dec 2021 14:28:36 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): channel closed`

Tue, 21 Dec 2021 14:28:26 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): channel closed`

Tue, 21 Dec 2021 14:28:16 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:28:07 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:27:57 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): channel closed`

Tue, 21 Dec 2021 14:27:46 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:27:27 GMT
ReqwestError: error sending request for url (https://chrysalis-nodes.iota.org/api/plugins/participation/events): connection closed before message completed

Tue, 21 Dec 2021 14:27:26 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:27:16 GMT
ReqwestError: error sending request for url (https://chrysalis-nodes.iota.org/api/plugins/participation/addresses/iota1qqc2nastd4q27antnttxrn22yxuup34rx5q5w3n4lkaxdcwy6ymjwxayhsd): connection closed before message completed

Tue, 21 Dec 2021 14:27:16 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/addresses/iota1qqc2nastd4q27antnttxrn22yxuup34rx5q5w3n4lkaxdcwy6ymjwxayhsd/outputs?include-spent=true): connection closed before message completed`

Tue, 21 Dec 2021 14:27:15 GMT
ReqwestError: error sending request for url (https://chrysalis-nodes.iota.org/api/plugins/participation/events): channel closed

Tue, 21 Dec 2021 14:26:50 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): channel closed`

**Comment by cvarley100** [comment]
Thanks @jperece. There was an issue with the node. It's fixed now 💪

**Comment by manikv12** [comment]
Its still giving error 
![image](https://user-images.githubusercontent.com/49544491/147416317-96de86e8-460f-4e9a-bbc8-ba2375b552bf.png)

**Comment by manikv12** [comment]
@cvarley100

**Comment by joergs-git** [comment]
Still doesn't work.... same message "Staking not detected"

Firefly v1.3.0
Language: en
Currency: EUR
Node selection: Automatic
Platform: macOS
Platform Version: 12.0.1
Platform Architecture: x64
CPU Count: 8
Total Memory: 16384.0 MB
Free Memory: 54.8 MB

**Comment by dx9oscar** [comment]
Doesn't work for me either with the same "Staking not detected" message

Firefly v1.3.0
Language: en
Currency: EUR
Node selection: Automatic
Platform: macOS
Platform Version: 12.1
Platform Architecture: x64
CPU Count: 8
Total Memory: 8192.0 MB
Free Memory: 39.8 MB

**Comment by dx9oscar** [comment]
Ah-ha found the workaround in #1894 

"Add https://mainnet-node.tanglebay.com/ to your nodes list and set it as primary. The default load balancers are having issues currently."
