### ISSUE TITLE
[Bug report]: Finding old balances fails

### ISSUE THREAD

**Issue by gjeee** [iotaledger/firefly#2202]
### Issue description

i have a couple of accounts in my wallet (the first three are empty though). now i tried recreating the wallet by using the 24words. however it is not able to finds the funds. also the balance-finder fails to find the balances.  

### Expected behaviour

the account & address space should be searched deep enough!

### Actual behaviour

funds are not found

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

1. create a wallet
2. create let's say 10 accounts and fund them
3. empty the funds on the first 3 accounts (and send them to the last few accounts)
4. try to restore the wallet by using the 24 words

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MiKeF05** [comment]
Can you try to restore your profile with the latest version 1.3.3? Should be solved now.

**Comment by gjeee** [comment]
v1.3.3 does not solve this issue

**Comment by MiKeF05** [comment]
How often have you used the balance finder? If you use the balance finder without closing the popup I guess Firefly will search further accounts. You can also join the official IOTA discord server to get help with this.

**Comment by MiKeF05** [comment]
@gjeee  There were some bug fixes for the balance finder. Can you try it again with the latest version?

**Comment by gjeee** [comment]
i just tried your new and improved balance finder (30 times) and still i can not recreate a multiple-wallet-profile by using its 24 words. maybe i have the wrong 24 words but i am fairly sure i have the right words. i still have a stronghold backup so no disaster but i was just curious to check if i could recreate my wallets with the 24 words approach.

**Comment by MiKeF05** [comment]
You used version 1.5.1? In the balance finder there should be some info how many wallets and addresses are searched

**Comment by begonaalvarezd** [comment]
Hi, is this still an issue in the latest version?

**Comment by gjeee** [comment]
I just tried it in v1.7.4 and problem persists (balance finder doesn't even search more than 1 wallet). So when restoring a profile consisting of multiple wallets by means of mnemonic, the balance finder fails since it doesn't search deep enough (wallet 2...wallet N).

**Comment by begonaalvarezd** [comment]
> I just tried it in v1.7.4 and problem persists (balance finder doesn't even search more than 1 wallet). So when restoring a profile consisting of multiple wallets by means of mnemonic, the balance finder fails since it doesn't search deep enough (wallet 2...wallet N).

We will release a new version very soon with the upgrade of mainnet to stardust, this new version comes with many improvements, search balance algorithm included

**Comment by marc2332** [comment]
Hello @gjeee, we just released the new version (v2.0.2 at time of writing this), could you give it a try and let us know if your issue is resolved? Thank you :smile: :v:

**Comment by begonaalvarezd** [comment]
Closing issue due to inactivity, please reopen if necessary 🌷
